#端口号
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 100
    min-spare-threads: 30
  port: 5353
#Spring 配置数据源
spring:
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/my_test?serverTimezone=Hongkong&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: 159357
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  main:
    allow-bean-definition-overriding: true
  data:
    redis:
      # 地址
      host: localhost
      # 端口，默认为6379
      port: 6379
      # 数据库索引
      database: 0
      # 密码
      password:
      # 连接超时时间
      timeout: 10s
      lettuce:
        pool:
          # 连接池中的最小空闲连接
          min-idle: 0
          # 连接池中的最大空闲连接
          max-idle: 8
          # 连接池的最大数据库连接数
          max-active: 8
          # #连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1ms
# Mybatis配置
mybatis:
    typeAliasesPackage: com.**.pojo
    mapperLocations: classpath:mapper/**/*.xml
#    configLocation: classpath:mybatis.xml