package com.mapper;

import com.pojo.Person;
import com.pojo.PersonExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PersonMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbg.generated Wed Oct 18 10:19:54 CST 2023
     */
    long countByExample(PersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbg.generated Wed Oct 18 10:19:54 CST 2023
     */
    int deleteByExample(PersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbg.generated Wed Oct 18 10:19:54 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbg.generated Wed Oct 18 10:19:54 CST 2023
     */
    int insert(Person row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbg.generated Wed Oct 18 10:19:54 CST 2023
     */
    int insertSelective(Person row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbg.generated Wed Oct 18 10:19:54 CST 2023
     */
    List<Person> selectByExample(PersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbg.generated Wed Oct 18 10:19:54 CST 2023
     */
    Person selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbg.generated Wed Oct 18 10:19:54 CST 2023
     */
    int updateByExampleSelective(@Param("row") Person row, @Param("example") PersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbg.generated Wed Oct 18 10:19:54 CST 2023
     */
    int updateByExample(@Param("row") Person row, @Param("example") PersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbg.generated Wed Oct 18 10:19:54 CST 2023
     */
    int updateByPrimaryKeySelective(Person row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbg.generated Wed Oct 18 10:19:54 CST 2023
     */
    int updateByPrimaryKey(Person row);
}